eureka:
  client:
    registerWithEureka: false

server:
  port: 8080

spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: song
          uri: http://localhost:8485
          predicates:
            - Path=/songs/**
        - id: playlist
          uri: http://localhost:8484
          predicates:
            - Path=/playlists/**