server:
  port: 8484

spring:
  application:
    name: playlist-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pdyc-playlist
    username: postgres
    password: admindb
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}