security.basic.enable: false
management.security.enabled: false
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AugustoGrecoUnnoba/TP6-pdyc2025-Pellizzari-Greco.git
