spring:
  application:
    name: song-microservice
  config:
    import: configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdyc-song
    username: postgres
    password: admindb
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true